### PR TITLE
Adds a function to enable QB to run query locally using im-tables

### PR DESCRIPTION
**Pull request by vivekkrish**
Hi @JoelRichardson,

This PR adds functionality to QB to allow users to run the query locally using the im-tables JS library. Thought this might be useful!

This PR makes the following changes:
+ Add necessary CSS and JS assets from im-tables-2.0.2 release
+ Update .gitignore

Please review this PR and feel free to accept/reject this change as you see fit.
Thank you for this wonderful tool!

### CODE REVIEW

**Comment by JoelRichardson** [comment]
Hi @vivekkrish ,

This looks great. Thank you!!

Joel

**Comment by JoelRichardson** [comment]
Hi @vivekkrish 
I'm *finally* getting around to testing this. This is great!! 
I think I'm going to merge the two buttons, and make running it locally the default.
Then shift-click to run it at the mine and alt-click to edit at the mine, or something like that.
Thanks again!

**Comment by JoelRichardson** [comment]
Hi @vivekkrish ,
This is now installed on the public site. Thanks again!

Joel

**Comment by vivekkrish** [comment]
Hi @JoelRichardson,

Thank you so much for accepting my changes, and fixing the erroneous <script /> tag. Apologies for the incomplete testing of different types of queries, I'm glad that you've expanded the getJson() method to fix the functionality.

**Comment by JoelRichardson** [comment]
No apologies needed! Thanks, @vivekkrish !

**Pull request merged**
